project:
  type: website
  output-dir: docs

website:
  title: "Learning Cloud Access Security Broker - Use-Cases"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: cloud-access-security-broker-foo.qmd
        text: Cloud Access Security Broker Foo

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: auto
